name: YAMLLint

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Read Python version
        id: python-version
        run: echo "::set-output name=version::$(cat .python-version)"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          grep yamllint requirements.txt | xargs -n 1 pip install

      - name: Lint YAML files
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git ls-files --exclude-standard --cached --others -- '*.yaml' '*.yml' | xargs yamllint
